### ISSUE TITLE
大佬，如果不集成 youtube-dl 和 ffmpg ，至少给个下载地址到wiki里。。

### ISSUE THREAD

**Issue by Scyllaly** [database64128/youtube-dl-wpf#1]

**Comment by database64128** [comment]
We already have links to the `youtube-dl` repo in the description and `README.md`. And I think it's pretty straight forward to get your own `ffmpeg` copy by either building from source or downloading pre-built binaries. Both `youtube-dl` and `ffmpeg` have very thorough instructions on their sites.

That being said, I'll update README.md to include more specific instructions and best practices on how to configure `youtube-dl-wpf` on the first run.

**Comment by database64128** [comment]
Documentation has been updated in 6343214f78e50a050f87ff5235a7801217d11229.
