### ISSUE TITLE
Abort download request doesn't abort the downloader

### ISSUE THREAD

**Issue by radiolondra** [database64128/youtube-dl-wpf#110]
Clicking the Abort button while downaloding some video, doesn't stop the download (even if the log in the textblock reports "Aborted").
The downloader (yt-dlp in my case) continues to download until it completes the job (video completely downloaded).
`dlProcess.Kill()` doesn't work as expected.

**Comment by database64128** [comment]
Thank you for reporting! This has been a known issue for a while. The problem with `yt-dlp` is that spawns a child process for downloading. Killing the main process won't stop the child process. I'm in the process of refactoring the code for backend support. The new code will properly send a `CTRL_C_EVENT` to gracefully stop the download process.

**Comment by radiolondra** [comment]
Also, in your string to double conversions, you should at least use `CultureInfo.InvariantCulture`, otherwise in countries where the decimal separator is "comma" (like here in Italy) calls like this one:

  ```
if (double.TryParse(percentageNumberString, out var percentageNumber))                    
  {
      ProgressPercentageValue = percentageNumber;                        
  }
```
  
will not work.

It could be changed in:
`ProgressPercentageValue = double.Parse(percentageNumberString, System.Globalization.CultureInfo.InvariantCulture);`

**Comment by database64128** [comment]
Thank you for letting me know! Feel free to open a PR so you can get the full credit for fixing this. 😄

**Comment by database64128** [comment]
[v1.11.0](https://github.com/database64128/youtube-dl-wpf/releases/tag/v1.11.0) has been released.
