### ISSUE TITLE
Use CultureInfo.InvariantCulture in YDW

### ISSUE THREAD

**Issue by radiolondra** [database64128/youtube-dl-wpf#111]
Reading the YDW code, in string to double conversions you should at least use `CultureInfo.InvariantCulture`, otherwise in countries where the decimal separator is "comma" (like here in Italy) calls like this one:

  ```
if (double.TryParse(percentageNumberString, out var percentageNumber))                    
  {
      ProgressPercentageValue = percentageNumber;                        
  }
```
  
will not work.

It could be changed in something like this:
`ProgressPercentageValue = double.Parse(percentageNumberString, System.Globalization.CultureInfo.InvariantCulture);`

**Comment by database64128** [comment]
Thank you for reporting! A fix is coming.
