### ISSUE TITLE
Request : x86 version

### ISSUE THREAD

**Issue by EDM115** [database64128/youtube-dl-wpf#126]
I wonder if it's possible to have this for 32bits windows systems

**Comment by database64128** [comment]
The framework-independent build (`youtube-dl-wpf-vx.x.x-windows.7z`) is `Any CPU` and can run on any supported architecture. You just have to install .NET runtime on your system.

**Comment by EDM115** [comment]
![F](https://user-images.githubusercontent.com/82015596/166140821-92b3f5f5-b1d6-47f0-b8db-dc03669ad68b.png)
I tried but it doesn't work

**Comment by database64128** [comment]
Do you have .NET 6 runtime installed on your system?

**Comment by database64128** [comment]
Try `dotnet ./youtube-dl-wpf.dll`.

**Comment by EDM115** [comment]
Thank youuuuu 🥺❤

**Comment by EDM115** [comment]
Then, adding a `YTdl.bat` with the other files for the any cpu release might help users like me :  
  
```batch
@ECHO OFF
TITLE Launch Youtube-DL
ECHO Launching...
ECHO Don't close this command window, else the YT downloader will close !
dotnet ./youtube-dl-wpf.dll
PAUSE
```

**Comment by database64128** [comment]
Or we can build binaries for 32-bit x86 and ARM targets. The next release will be out in a day or two, and will have binaries for these platforms.

**Comment by database64128** [comment]
See 76fe72faae368f3cc506714cbee3c3d945d95115 and bdaa2623dcc90ed904011c01b4f0a0168b4ab29e. https://github.com/database64128/youtube-dl-wpf/actions/runs/2257221141 Can you please try and see if the produced binaries work for you?

**Comment by database64128** [comment]
[v1.11.0](https://github.com/database64128/youtube-dl-wpf/releases/tag/v1.11.0) has been released.
