### ISSUE TITLE
.NET Framework, Qt, python

### ISSUE THREAD

**Issue by trimechee** [database64128/youtube-dl-wpf#129]
Hello, thank you very much for this awesome great downloader  !

Please i have questions, i have .NET Framework 4.8 advanced services installed by default on my windows 10, is it enough for Cube YouTube Downloader to work without bugs or do we absolutely should install .NET 6 Runtime?

can .NET 6 Runtime burden the computer and still work in the background even when you close Cube YouTube Downloader?

if so, it will be great if you can make a qt5 or qt6 or python version for weak notebooks that don't have much cpu power!

Thank you so much !

**Comment by database64128** [comment]
> can .NET 6 Runtime burden the computer and still work in the background even when you close Cube YouTube Downloader?

No. The runtime libraries are only loaded when you open the downloader. Nothing stays in the background.

> do we absolutely should install .NET 6 Runtime?

You don't have to install the runtime. Just download the self-contained binaries like `youtube-dl-wpf-v1.11.0-windows-x64.7z`. Only the framework-dependent version (`youtube-dl-wpf-v1.11.0-windows.7z`) requires an installed runtime.

**Comment by trimechee** [comment]
Wonderful ! Thank you very much for your precious help :)
