### ISSUE TITLE
Standard or special version of FFmpeg

### ISSUE THREAD

**Issue by trimechee** [database64128/youtube-dl-wpf#130]
Hello, thank you very much for adding preset especially the worst audio preset that we can enable with a single one click and which allows us to download  audio of the videos very quickly and put them in our smartphones without draining the battery or listening to tv shows when we sleep leaving the computer screen extinct !!

It's very rare exceptional to have this important preset and to be able to quickly download the worstaudio with just one click!!! thank you so much !!

just to wonder because I saw in the description "Optionally but recommended, get ffmpeg either by building from source or downloading pre-built binaries for Windows.", this takes us to the classic version of FFmpeg, but I discovered there is a special builds of FFmpeg for yt-dlp to fix some bugs,should we use this special builds of FFmpeg to fix some bugs for example :

[Fix AAC HLS streams being truncated mid stream]

[Fix for YouTube's VP9 encodes with non-monotonous DTS]

or should we use the classic version of FFmpeg ?

https://github.com/yt-dlp/FFmpeg-Builds

**Comment by database64128** [comment]
I wasn't aware of the existence of yt-dlp's patched ffmpeg. From the project description it seems like it's just a fork with some patches that haven't been merged by the upstream yet. Unless you really need the features in the [applied patches](https://github.com/yt-dlp/FFmpeg-Builds#patches-applied), it really doesn't matter what version of ffmpeg to use.

**Comment by trimechee** [comment]
Ohh if I understood correctly, the official version of FFmpeg on the official site of FFmpeg already contains these patches? Thank you very much for these clarifications :)

**Comment by database64128** [comment]
> Ohh if I understood correctly, the official version of FFmpeg on the official site of FFmpeg already contains these patches?

Yes.

**Comment by trimechee** [comment]
Great 👍
