### ISSUE TITLE
custom arguments not accepted

### ISSUE THREAD

**Issue by andekande** [database64128/youtube-dl-wpf#141]
In current release no extra arguments are accepted by both backends. Example:

yt-dlp: error: no such option: --add-header Referer:https://someurl.com/
youtube-dl.exe: error: no such option: --add-header Referer:https://someurl.com/

yt-dlp: error: no such option: --version
youtube-dl.exe: error: no such option: --version

**Comment by andekande** [comment]
I see, and can confirm I have to add two chips. Well, maybe a tabular view is more self-explanatory. Since the argument value Referer is belonging to --addHeader. It can not be used standalone.

**Comment by database64128** [comment]
> Well, maybe a tabular view is more self-explanatory.

You wouldn't feel this way if you are familiar with how command-line arguments work. :P
