### ISSUE TITLE
very slow to open on windows

### ISSUE THREAD

**Issue by ghost** [database64128/youtube-dl-wpf#153]
this application seems to take a very long time to open on windows, taking anywhere from 30 seconds to even couple minutes at times. sometimes it will also lose all my settings like paths for yt-dlp, ffmpeg, custom download location etc.

**Comment by database64128** [comment]
Is this slowness specific to this application, or everything else is also not very responsive on your system? Please provide more information on your situation:

- Windows version.
- Are you running Windows on an SSD or an HDD?
- youtube-dl-wpf version and which release file.
