### ISSUE TITLE
Define Custom Download path %(playlist)s folder

### ISSUE THREAD

**Issue by intelati26** [database64128/youtube-dl-wpf#158]
One feature from the CMD I can't get to work is the playlist name folder...

Whenever I have the download path set to a folder like that, I'm unable to get the download button to work. 

The output flag looks fine to me, but not sure why it's not letting me hit go on it. 
![image](https://user-images.githubusercontent.com/11883481/190857991-ea54c435-67be-4371-9052-65458b85c32f.png)

**Comment by intelati26** [comment]
Maybe I should try more.... 

Use this template
![image](https://user-images.githubusercontent.com/11883481/190867294-139b1258-2939-4a09-8a32-de1ee3f78ceb.png)

**Comment by database64128** [comment]
Glad to hear you found a solution. The GUI checks the download path, and only lets you click the download button when the directory pointed by the path exists. Do you think I should remove the check, or are you satisfied with the solution?
