### ISSUE TITLE
Subtitle

### ISSUE THREAD

**Issue by NethalDeveloper** [database64128/youtube-dl-wpf#159]
Hi Add Subtitle Auto Generator
**Thanks**

**Comment by database64128** [comment]
Hi, what is a "Subtitle Auto Generator"?

Thanks.

**Comment by NethalDeveloper** [comment]
Optional YouTube video subtitles

**❤🙌**

**Comment by database64128** [comment]
This is already supported. Just select all three:

![image](https://user-images.githubusercontent.com/18757988/190902649-7184aaa5-e2ef-48f3-9240-4f842679f3f6.png)

**Comment by NethalDeveloper** [comment]
You didn't understand what I meant, but ok😂❤

Thanks

**Comment by database64128** [comment]
Then help me understand, thanks.
