### ISSUE TITLE
options download playlist (--playlist-start --playlist-end)

### ISSUE THREAD

**Issue by amorfiniluigi82** [database64128/youtube-dl-wpf#165]
Hi, my name is Luigi write from Italy.. I would like to know how to use --playlist-start and --playlist-end commands.

Best regards.

**Comment by database64128** [comment]
`--playlist-start` and `--playlist-end` are CLI options, not commands. You can add these to the argument list in the main interface, or create a custom preset with these arguments.

**Comment by database64128** [comment]
It is also possible to use `--playlist-items` with a range. Would it be more convenient for you if I add this to the GUI?

**Comment by amorfiniluigi82** [comment]
My screen shot ? how to use cli options??
![image](https://user-images.githubusercontent.com/123329788/233983787-114ae9ac-cce9-41b5-bd42-b8e5475c7173.png)

**Comment by database64128** [comment]
`--playlist-end` and `25` are two separate arguments. You need to add them separately.

**Comment by amorfiniluigi82** [comment]
ok, problem solved .. thanks

**Comment by database64128** [comment]
Support for `--playlist-items` has been added in 05777f534b70e8ca6c496681f0ef96b0cb8fcf5c.

**Comment by database64128** [comment]
[v1.12.0](https://github.com/database64128/youtube-dl-wpf/releases/tag/v1.12.0) is out with the new feature.
