### ISSUE TITLE
[Feature] Filename template history

### ISSUE THREAD

**Issue by Iongtimenosee** [database64128/youtube-dl-wpf#166]
The tool is the best GUI tool I've ever used. Thanks to the author!!! Sometimes I want to download playlists, sometimes I want to download individual files, so I would like to have multiple "Custom filename template" functionalities. Can it be made into a dropdown menu with a history record just like the existing "Custom download path" functionality?

**Comment by database64128** [comment]
Sounds like a reasonable feature request. I'll probably implement it this weekend.

**Comment by database64128** [comment]
Implemented in e37e68135df7f779a321869f96acb89a83401402.

**Comment by Iongtimenosee** [comment]
excellent!

**Comment by database64128** [comment]
[v1.12.0](https://github.com/database64128/youtube-dl-wpf/releases/tag/v1.12.0) is out with the new feature.
