### ISSUE TITLE
[Readme] Dead link

### ISSUE THREAD

**Issue by EDM115** [database64128/youtube-dl-wpf#169]
The [FFMPEG link](https://ffmpeg.zeranoe.com/builds/) is dead  
![image](https://github.com/database64128/youtube-dl-wpf/assets/82015596/251ef401-450d-4a00-b8a9-3c3c0bbbcf82)
  
I recommend using https://www.gyan.dev/ffmpeg/builds/ instead

**Comment by database64128** [comment]
Thanks for reporting this. I think using https://ffmpeg.org/download.html would be a more permanent solution.
