### ISSUE TITLE
Bug : Hitting enter on the link field makes the app freeze then crash

### ISSUE THREAD

**Issue by EDM115** [database64128/youtube-dl-wpf#171]
Just as the title says.  
v1.12.1.0

**Comment by database64128** [comment]
Thank you for reporting this. This bug was introduced back in v1.12.0. I'm surprised no one has opened an issue until now. Looks like we need another patch release.

**Comment by database64128** [comment]
[v1.12.2](https://github.com/database64128/youtube-dl-wpf/releases/tag/v1.12.2) is out.
