### ISSUE TITLE
[small visual issue] Make the background the same everywhere

### ISSUE THREAD

**Issue by EDM115** [database64128/youtube-dl-wpf#176]
This issue will probably affect no one except me  
When using 3rd-party programs that allows transparency of windows (here [MicaForEveryone](https://github.com/MicaForEveryone/MicaForEveryone)), we can see that the effect is cast to the main parts of the window, text fields, contour of buttons, ...  
But I wonder if it's possible to view it on the whole window 👀   
  
Screenshots :  
![MicaForEveryone display](https://github.com/database64128/youtube-dl-wpf/assets/82015596/eb5af658-69c3-434a-a001-6fa0516193ae)
![MicaForEveryone settings display](https://github.com/database64128/youtube-dl-wpf/assets/82015596/351f5c77-b1d6-403b-88ac-6d203afe6197)

**Comment by database64128** [comment]
youtube-dl-wpf uses [MaterialDesignThemes](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit) unmodified. You'd have better luck getting this resolved by opening an issue at MicaForEveryone about the problems with **WPF apps that use MaterialDesignThemes**.
