### ISSUE TITLE
yt-dlp arguments not available

### ISSUE THREAD

**Issue by Zoxjib** [database64128/youtube-dl-wpf#180]
Adding arguments that work with yt-dlp via terminal report an error in youtube-dl-wpf:

`yt-dlp.exe: error: no such option: --cookies cookies.txt`
`yt-dlp.exe: error: no such option: --cookies-from-browser chrome`

**Comment by database64128** [comment]
`--cookies` and `cookies.txt` are two separate arguments, not one. Same with `--cookies-from-browser` and `chrome`.
