### ISSUE TITLE
Allow download of videos or audio within a date range

### ISSUE THREAD

**Issue by jeno1712** [database64128/youtube-dl-wpf#195]
Within the GUI I tried to pass `--dateafter 20240202` to use the date range function of the `yt-dlp` to download a youtube playlist. I passed this as an argument in the settings menu, the run before startup argument and also as an argument within the download section. But the GUI this is returning an error `yt-dlp.exe: error: no such option: --dateafter 20240202`.

I know that yt-dlp supports downloading a playlist within a date range and it works in the commandline without the GUI. May be this isn't implemented within the GUI. If this isn't implemented within the GUI can you please implement it or if this feature is already available within the GUI can you please tell me the format to  pass the date range argument for downloading the playlist within a date range

**Comment by database64128** [comment]
`--dateafter` and `20240202` are two separate arguments, not a single one.

**Comment by jeno1712** [comment]
Oh I see. Thankyou for the quick reply. Now it works.

**Comment by database64128** [comment]
See also: #141, #161
