### ISSUE TITLE
如果我要下载指定格式，怎么指定呢。。

### ISSUE THREAD

**Issue by Scyllaly** [database64128/youtube-dl-wpf#2]

**Comment by database64128** [comment]
First use the "List Formats" button to ask `youtube-dl` to list all available formats. To specify the video and audio format, toggle "Override Formats" and fill in the format numbers, as shown in the screenshots embedded in README.md.

And please use English for issues. Non-English issues will be ignored and closed from now on.

**Comment by Scyllaly** [comment]
got it ,thx
