### ISSUE TITLE
Settings that affect download speed

### ISSUE THREAD

**Issue by Korb** [database64128/youtube-dl-wpf#207]
Currently, when using Cube YouTube Downloader (aka youtube-dl-wpf) version 1.12.2.0 and yt-dlp 2024.07.25 x64, I observe video download speeds of around 1.5-2.0 Mbps. This is very slow considering that when using yt-dlp directly and when downloading other files, I can observe download speeds of up to 100 Mbps.

I suggest considering the possibility of specifying parameters in the Cube YouTube Downloader interface that will allow more complete use of the Internet connection bandwidth (and significantly reduce the waiting time if technically possible).

**Comment by database64128** [comment]
This is not possible, as all youtube-dl-wpf does is fundamentally the same thing as when you manually execute yt-dlp. There are no hidden command-line arguments. You should compare the arguments displayed in the UI with the ones you specify by hand and see what's causing the difference.
