### ISSUE TITLE
request support for non youtube

### ISSUE THREAD

**Issue by c4c1n6kr3m1** [database64128/youtube-dl-wpf#209]
i tested this app yesterday and i like it
can you add support for non youtube in option, like
--no-check-certificates
--referer
--concurrent-fragments
-c
and --user-agent

**Comment by database64128** [comment]
Not sure I understood what you mean, but you can always specify custom arguments.

**Comment by c4c1n6kr3m1** [comment]
i know that i can use custom argument
i want it in fixed input
rather than using custom arguments

**Comment by database64128** [comment]
Well, you'll have to convince me with very good reasons, if you want dedicated controls in the UI for these flags. You can't just slap a list of options on my face and demand to have the UI updated for them.

**Comment by c4c1n6kr3m1** [comment]
it's quite common for video platform outside mainstream platform need some adjustment like referer or cookies
i can not convince you otherwise , sorry for bad eanglish
