### ISSUE TITLE
How to change UI language manually?

### ISSUE THREAD

**Issue by AspirinEny** [database64128/youtube-dl-wpf#62]
I noticed the latest release inclued some specific language resource files, can I change the UI language manually? Thanks for your reply.
Sincerely.

**Comment by database64128** [comment]
Thank you for your interest in this project! The project itself doesn't have translations, and I have no intention to add any in the future. The language resource files you saw are from the bundled .NET runtime in self-contained packages. The framework-dependent packages don't have these files.

**Comment by AspirinEny** [comment]
I see. Thanks.
