### ISSUE TITLE
Can I use this repo to do the job like yt-dlp?

### ISSUE THREAD

**Issue by zydjohnHotmail** [database64128/youtube-dl-wpf#91]
Hello:
I found one web site, which I can see live sports video, and using the tool yt-dlp 
https://github.com/yt-dlp/yt-dlp
I can download the underlying m3u8 link.
One example is something like:

yt-dlp https://m3u8.1proxy.xyz/media/g_18/playlist.m3u8 --downloader ffmpeg --referer "https://bingsport.com/"

You can find some live streams from the following URL: 
(# can be a number from 1 to 20 or 30 depend on how many live games have for today).
https://bingsport.com/1proxy.php?id=g_#

But I can’t use youtube-dl.exe to do the same, as the parameters are different from yt-dlp.
Let me know if I can do the job like yt-dlp does with this repo?  As I need API library in C# for my project.
Thanks,

**Comment by database64128** [comment]
`youtube-dl-wpf` isn't just a GUI for `youtube-dl`. Support for `yt-dlp` was added in v1.8. If you want external downloader support, please look at #83.

**Comment by database64128** [comment]
Support for custom command-line arguments has been added in c54c1aebaedfe30f6e0401a2d6ce0fb36716f06f. See https://github.com/database64128/youtube-dl-wpf/issues/83#issuecomment-978110848 for details.
