### ISSUE TITLE
Suggestion to update GUI to reflect update is to both youtube-dl and yt-dlp

### ISSUE THREAD

**Issue by noto10** [database64128/youtube-dl-wpf#92]
Does the '**Update youtube-dl on startup**' apply to **yt-dlp** as well?

If so, perhaps it would be a good idea to indicate this to avoid confusion.

![youtube-wpf tmp](https://user-images.githubusercontent.com/13828004/142252501-25993160-d063-4445-981e-98aade34bd07.jpg)

**Comment by database64128** [comment]
Yes, it works with `yt-dlp` as well. I'll change the text.

**Comment by database64128** [comment]
Done in 8f2701b181aa36e26560f6b5cef680ea797988ce.
