### ISSUE TITLE
"custom download path"-a droplist button-like

### ISSUE THREAD

**Issue by kimycai** [database64128/youtube-dl-wpf#93]
hi nice developer，i want to talk about the "custom download path"again.Could it also be a droplist button-like that can remember the historical path so that I can select the path I put before easily without typing the path .

**Comment by database64128** [comment]
![image](https://user-images.githubusercontent.com/18757988/142752575-7a6843ac-4db6-4537-92d2-62471d496ea3.png)

Done in 8f2701b181aa36e26560f6b5cef680ea797988ce. The current path is saved after clicking the download button. You can download the binaries from https://github.com/database64128/youtube-dl-wpf/actions/runs/1486286330.
